language: android
notifications:
  email: false
sudo: false
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
jdk:
- oraclejdk8
script:
- "./gradlew assembleRelease"
before_deploy: mv app/build/outputs/apk/app-debug.apk app/build/outputs/apk/Gank.apk
deploy:
  provider: releases
  file: app/build/outputs/apk/Gank.apk
  skip_cleanup: true
  on:
    tags: true
before_install:

- openssl aes-256-cbc -K $encrypted_9764c1140142_key -iv $encrypted_9764c1140142_iv
  -in app/google-services.json.enc -out app/google-services.json -d
