language: android   # 声明构建语言环境

notifications:
  email: false

sudo: false         # 开启基于容器的Travis CI任务，让编译效率更高。

android:            # 配置信息
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository     # Android Support Repository
    - extra-android-support          # Support Library

jdk:
- oraclejdk8

script:              # 执行:下面的命令
  - ./gradlew assembleRelease

before_deploy:       # 部署之前
  # 使用 mv 命令进行修改apk文件的名字
  mv app/build/outputs/apk/app-debug.apk app/build/outputs/apk/buff.apk

deploy:              # 部署
  provider: releases
  file: app/build/outputs/apk/Gank.apk   # 部署文件路径
  skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
  on:     # 发布时机
    tags: true       # tags设置为true表示只有在有tag的情况下才部署
